lexer grammar FOkLexer;

LPAREN: '(';
RPAREN: ')';
EQUALS: '=';
TRUE: [Tt][Rr][Uu][Ee];
FALSE: [Ff][Aa][Ll][Ss][Ee];
FORALL: [fF][Oo][Rr][Aa][Ll][Ll];
EXISTS: [Ee][Xx][Ii][Ss][Tt][Ss];
AND: '&';
OR: '|';
IMPLIES: '->';   
IFF: '<->';
NOT: '~';
CONST: '#' [A-Za-z0-9]+;
FUNC: '_' [A-Za-z0-9]+;
RELATION: [A-Z0-9]+;       
VARIABLE: [a-zA-Z][a-zA-Z0-9]*;
DOT: '.';
COMMA: ',';
ENDLINE: ('\r'|'\n')+ -> skip;
WS: [ \t]+ -> skip;
COMMENT: '//' ~('\t'|'\r'|'\n')*  '\r'? '\n' -> skip;
